#-------------------------------
# Site Settings

title: Chaam Company
logo: # You can add own logo. For example '/images/logo.png'.
description: 참컴퍼니 공식 홈페이지

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Elements'

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Chaam Company
  title: Hello we're Chaam Company
  bio: Chaam Company는 iOS 개발 공부를 하는 사람들과 디자이너, 기획자, 촬영팀이 모여 구성된 팀 입니다. 함께 앱을 개발하고 해커톤 행사를 기획하며 같이 공부하고 성장하는데에 목표를 두고 있습니다.
  image: '/images/01.png'
  avatar: '/images/avatar.png'
  button__text: See my works


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Works</span> # Add a 'text-span' class to highlight text.
  projects__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section

testimonial__title: Our Team <span class="text-span">Members</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "이창형(Changbro)"
    image: "/images/member-changbro.jpeg"
    designation : "Developer"
    content : "iOS 개발자 Begginer 이창형입니다. 맡은 일에 대한 책임감이 강하고 무슨 일이든 능동적인 자세로 포기하지 않고 노력합니다. 호기심과 도전정신이 강하여 여러 분야의 경험도 많습니다."

  - name: "홍정민(Chikong)"
    image: "/images/member-chikong.jpeg"
    designation : "Developer"
    content : "실패를  두려워하지 않고, 도전하며 성장을 즐기면서 iOS App 개발공부를 하고있는 홍정민 입니다. 협업을 통해 "

  - name: "정윤성(Neis)"
    image: "/images/member-neis.JPG"
    designation : "Deigner & Developer"
    content : "반갑습니다! 제 이름은 정윤성입니다. 저는 기획, 디자인, 개발 모든 것을 다 하는 풀스택 디자이너를 꿈꾸는 학생입니다. 현재 UX 관점에서 서비스 기획을 하기 위해 노력 중입니다."

  - name: "곽세진(Raven)"
    image: "/images/client-4.jpg"
    designation : "PM & Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "이재웅(Curry)"
    image: "/images/client-4.jpg"
    designation : "Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "최원혁(Hyukey)"
    image: "/images/client-4.jpg"
    designation : "Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "이준모(Bethev)"
    image: "/images/client-4.jpg"
    designation : "Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-github", link: "https://github.com/CHAAM-Company"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/chaamcompany_official/"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
