#-------------------------------
# Site Settings

title: Chaam Company
logo: # You can add own logo. For example '/images/logo.png'.
description: 참컴퍼니 공식 홈페이지

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Elements'

# Call to action button
cta__button__text: 문의 하기

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Chaam Company
  title: Chaam Company 방문을 환영합니다.
  bio: Chaam Company는 iOS 개발 공부를 하는 사람들과 디자이너, 기획자, 촬영팀이 모여 구성된 팀 입니다. 함께 앱을 개발하고 해커톤 행사를 기획하며 같이 공부하고 성장하는데에 목표를 두고 있습니다.
  image: '/images/01.png'
  avatar: '/images/avatar.png'
  button__text: 작업물 보러가기


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: 최근 <span class="text-span">작업물</span> # Add a 'text-span' class to highlight text.
  projects__description: Chaam Company 팀원들이 기획하고 개발했던 <br>작업물들을 소개하겠습니다!


#-------------------------------
# Testimonials Section

testimonial__title: Chaam Company의 <span class="text-span">구성원들</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "이창형(Changbro)"
    image: "/images/profile/member-changbro.jpeg"
    designation : "Developer"
    content : "iOS 개발자 Begginer 이창형입니다. 맡은 일에 대한 책임감이 강하고 무슨 일이든 능동적인 자세로 포기하지 않고 노력합니다. 호기심과 도전정신이 강하여 여러 분야의 경험도 많습니다."

  - name: "홍정민(Chikong)"
    image: "/images/profile/member-chikong.jpeg"
    designation : "Developer"
    content : "실패를 두려워하지 않고, 도전하며 성장을 즐기면서 iOS App 개발공부를 하고있는 홍정민 입니다. 협업을 통해 경험을 쌓고 커뮤니케이션 스킬을 배우며 성장하고 있습니다."

  - name: "정윤성(Neis)"
    image: "/images/profile/member-neis.JPG"
    designation : "Designer & Developer"
    content : "반갑습니다! 제 이름은 정윤성입니다. 저는 기획, 디자인, 개발 모든 것을 다 하는 풀스택 디자이너를 꿈꾸는 학생입니다. 현재 UX 관점에서 서비스 기획을 하기 위해 노력 중입니다."

  - name: "곽세진(Raven)"
    image: "/images/profile/member-raven.jpeg"
    designation : "PM & Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "이재웅(Curry)"
    image: "/images/profile/member-curry.jpeg"
    designation : "Developer"
    content : "안녕하세요! 항상 새로운 것을 만들고자 하는 개발자, 이재웅입니다. 저는 iOS 개발을 하고 있으며 iOS 생태계와 문화를 만들고 경험하며 세상에 이로운 제품을 만들고자 합니다."

  - name: "최원혁(Hyukey)"
    image: "/images/profile/noImg.jpg"
    designation : "Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "이준모(Bethev)"
    image: "/images/profile/noImg.jpg"
    designation : "Developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
    
  - name: "전호정(Lau)"
    image: "/images/profile/member-라우.jpeg"
    designation : "UI/UX Designer & Degital Creator"
    content : "안녕하세요 개발자,기획자와 소통이 가능한 올라운더 디자이너가 되고싶은 전호정입니다!\nUI/UX 뿐만 아니라 디지털 크리에이터로서도 열심히 성장하려 노력하고 있습니다!"
    
  - name: "강지인(Jeni)"
    image: "/images/profile/member-Jeni.png"
    designation : "Developer"
    content : "안녕하세요~ 개발자 강지인입니다. 무엇이든 함께, 즐겁게, 행복하게, 책임감 있게 해내는 사람입니다. 사람을 가장 중요시하며 개발에서나, 사람 사이에서나 윤활유같은 존재가 되겠습니다."
    
  - name: "한경준(Halogen)"
    image: "/images/profile/member-halogen.jpeg"
    designation : "Developer"
    content : "안녕하세요! 디발자를 꿈꾸는 한경준입니다. Apple 생태계 안에서의 소프트웨어 개발과 디자인을 공부하고 있습니다. 유저에게 사랑받는 앱을 개발하기 위해 노력중입니다."
    
  - name: "신제범(Garfield)"
    image: "/images/profile/member-Garfield.jpeg"
    designation : "Media Desginer"
    content : "안녕하세요! 미디어 디자이너 신제범 입니다. 저는 방위산업, 과학기술, 교육 분야의 미디어 컨텐츠를 기획하고 제작합니다. 많은 사람들에게 기획한 컨텐츠를 사진과 영상을 통해 영향력 있게 전달하기 위해 노력 중입니다."
    
  - name: "안태우(Thomas)"
    image: "/images/profile/member-Thomas.jpeg"
    designation : "Video Artist"
    content : "비디오 아티스트를 꿈꾸는 안태우 입니다. 저는 방송이나 영화 등에 쓰이는 카메라 및 각장 촬영 장비를 다루고 있고 그 밖에도 기획 및 각본등에도 기여하고 있으며 소프트웨어로는 어도비 프리미어와 애프터 이팩트등을 다루고 있습니다."
    
  - name: "노건영(Andrew)"
    image: "/images/profile/member-Andrew.jpeg"
    designation : "PD"
    content : "안녕하세요! 영상편집 프로듀서를 희망하는 노건영입니다 저는 산업적 디자인 교류와 방송 분야의 기획방식을 배우며 2D, 3D와 같은 미디어 아트의 트렌드를 새로 제작하는 방식과 영상 매체로서 디지털미디어디자인 시장에 참여하기 위한 준비를 하고있습니다"
    
  - name: "김도운(Ben)"
    image: "/images/profile/member-ben.jpeg"
    designation : "Media Artist"
    content : "안녕하세요! 미디어 아티스트를 꿈꾸는 김도운입니다. 저만의 미디어 컨텐츠 제작을 최종 목표로 프리미어 프로, 에프터 이펙트 등 어도비 프로그램을 이용한 편집을 배우며 다양한 영상 미디어 컨텐츠를 제작해오고 있습니다."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: 최근 <span class="text-span">이벤트</span> 내용 # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">블로그</span> 구독하기 # Add your title
  mailchimp__text: " '메일을 입력하시면', '업데이트 사항을 받아보실수 있습니다!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: 구독하기 # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-github", link: "https://github.com/CHAAM-Company"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/chaamcompany_official/"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
